dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decideprueba password 'complexpassword'"
- psql -U postgres -c "create database decideprueba owner decideprueba"
- psql -U postgres -c "ALTER USER decideprueba CREATEDB"
language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
- pip install django-chartjs
- pip install coverage
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- ./manage.py makemigrations
- ./manage.py migrate
- coverage run --branch --source=. ./manage.py test census --keepdb
